version: '3.8'

services:
  frontend:
    build: ./frontend
    image: frontend:build
  backend:
    build: ./backend
    command: flask --app src/main run --host=${WWW_HOST} --port ${WWW_PORT} --debug
    volumes:
      - ./backend/src/:/usr/src/app/src
    ports:
      - ${WWW_PORT}:${WWW_PORT}
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgrespw
      - DB_NAME=chess
      - DB_PORT=5432
    depends_on:
      - frontend
      - db
  db:
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=chess

volumes:
  postgres_data: